---
language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
env:
  - ANSIBLE_PIP='ansible==2.8.*'
  - ANSIBLE_PIP='ansible==2.9.*'
dist: bionic

addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install "$ANSIBLE_PIP"

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - cd tests; ./run_tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
