---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install yamllint

    # Check ansible version
  - ansible --version

    # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - cd tests; ./run_tests.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
